backend:
  name: github
  repo: yahsan2/netlify-test

base_url: romantic-kepler-7dfe0a

media_folder: media_folder

collections:
  - name: post
    label: Post
    folder: posts
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}

  - name: article
    label: Article
    folder: articles
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
